### ISSUE TITLE
$__DIR__ undefined variable in boot() 

### ISSUE THREAD

**Issue by domainregistrar** [fomvasss/laravel-punycode#1]
`
   ErrorException  : Undefined variable: __DIR__

  at /Users/user/Desktop/Projects/project/vendor/fomvasss/laravel-punycode/src/PunycodeServiceProvider.php:17
    13|      */
    14|     public function boot()
    15|     {
    16|         $this->publishes([
    17|             $__DIR__ . '/../config/punycode.php' => config_path('punycode.php')
    18|         ], 'config');
    19| 
    20|         $this->registerHelpers();
    21|     }
`

Should replace $__DIR__ with __DIR__ and this works.

This breaks publishing config/composer update.

**Comment by fomvasss** [comment]
Thanks. I fixed the error!

**Comment by domainregistrar** [comment]
@fomvasss Awesome quick response! 👍
